export const LANGUAGE_NAMES: Record<string, string> = {
  EN: 'English',
  ES: 'Spanish',
  FR: 'French',
  DE: 'German',
  IT: 'Italian',
  PT: 'Portuguese',
  RU: 'Russian',
  ZH: 'Chinese',
  JA: 'Japanese',
  KO: 'Korean',
  AR: 'Arabic',
  HI: 'Hindi',
  BN: 'Bengali',
  PA: 'Punjabi',
  JV: 'Javanese',
  MS: 'Malay',
  TL: 'Tagalog',
  VI: 'Vietnamese',
  TR: 'Turkish',
  PL: 'Polish',
  UK: 'Ukrainian',
  NL: 'Dutch',
  EL: 'Greek',
  HU: 'Hungarian',
  SV: 'Swedish',
  CS: 'Czech',
  DA: 'Danish',
  FI: 'Finnish',
  NO: 'Norwegian',
  HE: 'Hebrew',
  TH: 'Thai',
  ID: 'Indonesian',
  FA: 'Persian',
  UR: 'Urdu',
  RO: 'Romanian',
  SK: 'Slovak',
  BG: 'Bulgarian',
  SR: 'Serbian',
  HR: 'Croatian',
  LT: 'Lithuanian',
  SL: 'Slovenian',
  ET: 'Estonian',
  LV: 'Latvian',
  SQ: 'Albanian',
  MK: 'Macedonian',
  HY: 'Armenian',
  KA: 'Georgian',
  AZ: 'Azerbaijani',
};

export function getLanguageName(code: string): string {
  if (!code) return 'Uncategorized';
  const normalized = code.toUpperCase();
  return LANGUAGE_NAMES[normalized] || code;
}
